### ISSUE TITLE
Source de icons

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/practicaIDI#1]
Font d'on treure les icones per a mantenir estabilitat a la app

**Comment by elena20ruiz** [comment]
Proposo aquestes dues a veure que et semblen: 

*Pel tema de películes:* http://www.flaticon.com/packs/movies-5
*Pel tema general:* http://www.flaticon.com/packs/essential-collection
totes dues s'assemblen per això he pensat en aquestes

**Comment by daleu** [comment]
Weeeee! Hem Sambla good! 💃
